[tool.poetry]
name = "rect-todo"
version = "0.1.0"
description = ""
authors = ["rebo <rebo@mahusai.ph>"]

[tool.poetry.dependencies]
python = "^3.10"
node = "^1.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
